In [16]:
import os
import ast
from typing import Dict

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from dotenv import load_dotenv

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.multi_sparse', True)
pd.set_option('display.max_rows', 300)

load_dotenv(dotenv_path="/weka/home/adeluci2/scratch-mdredze1/adeluci2/Multi-Document-Summarization-Analysis/.env")

PROJECT_DIR = os.environ["MDS"]

In [17]:
metric_name_map = {
    "rouge_rouge1": "R-1",
    "rouge_rougeL": "R-L",
    "rouge_rougeLsum": "R-LSum",
    "moverscore": "Mover.",
    "unieval_relevance": "Rel. (UE)",
    "unieval_factuality": "Fact. (UE)", 
    "unieval_fluency": "Flue. (UE)",
    "unieval_coherence": "Coh. (UE)",
    "compression_sentence": "Comp.-Sent.",
    "compression_token": "Comp.-Word",
    "bertscore_recall": "BERTS. R",
    "bertscore_precision": "BERTS. P",
    "bertscore_f1": "BERTS. F1"
}

metric_to_category = {
    "rouge_rouge1": "Ground-Truth Similarity",
    "rouge_rougeL": "Ground-Truth Similarity",
    "rouge_rougeLsum": "Ground-Truth Similarity",
    "moverscore": "Ground-Truth Similarity",
    "unieval_relevance": "Ground-Truth Similarity",
    "unieval_factuality": "Factuality", 
    "unieval_fluency": "Quality",
    "unieval_coherence": "Quality",
    "compression_sentence": "Quality",
    "compression_token": "Quality",
    "bertscore_recall": "Ground-Truth Similarity",
    "bertscore_precision": "Ground-Truth Similarity",
    "bertscore_f1": "Ground-Truth Similarity"
}

dataset_name_map = {
    "convosumm": "Conv. Reddit",
    "convosumm/reddit": "Conv. Reddit",
    "multixscience": "XScience",
    "multinews_plus": "News+"
}

def get_model_type(raw_model_name: str) -> str:
    if "PRIMERA" in raw_model_name:
        return "PRIMERA"
    if "ICL" in raw_model_name:
        raw_model_name = raw_model_name.replace("ICL", "Llama 3.1")
    if "Llama 3.1" == raw_model_name:
        raw_model_name = "Llama 3.1 (0-shot)"
    else:
        raw_model_name = raw_model_name.split("-")[0]
    return raw_model_name


def get_train_domain(row: pd.Series) -> str:
    if row.model == "ground_truth":
        return dataset_name_map[row.dataset]
    if "icl" == row.model.lower():
        return "zero-shot"
    else:
        return dataset_name_map[row.model.split("-")[-1].lower()]


def format_entry(entry: str) -> Dict[str, float]:
    try:
        entry = ast.literal_eval(entry)
    except ValueError as err:
        print(f"Could not convert '{entry}' as literal")
        return pd.NA
    return entry
 

def load_aggregated_results(path: str) -> pd.DataFrame:
    # Load CSV. First two rows are header columns.
    df = pd.read_csv(path, header=[0,1])
    # Flatten the columns multi-index
    df.columns = pd.Index([
      f"{c[0]}_{c[1]}" if c[1]!="nan" else c[0] for c in df.columns
    ])
    metric_cols = [c for c in df.columns if c not in {"run_id", "model", "dataset", "split"}]
    
    # Convert the dictionaries from strings
    # and expand into individual columns
    # for col in metric_cols:
    #     df[col] = df[col].map(format_entry)
    #     for stat in ["mean", "std", "ci_std"]:
    #         df[f"{col}_{stat}"] = df[col].map(lambda x: x if pd.isna(x) else x[stat])
    #     df[f"{col}_ci_lower"] = df[col].map(lambda x: x if pd.isna(x) else x["ci"][0])
    #     df[f"{col}_ci_upper"] = df[col].map(lambda x: x if pd.isna(x) else x["ci"][1])

    df["dataset_test"] = df["dataset"].map(lambda x: dataset_name_map.get(x, x))
    df["dataset_train"] = df.apply(get_train_domain, axis="columns")
    df["model_type"] = df.model.map(get_model_type)
    df["in_domain"] = df.apply(lambda x: x.dataset_train==x.dataset_test, axis="columns")

    # --- 2. Data Transformation (from Wide to Long Format) ---
    # This part parses the string columns and reshapes the DataFrame.
    # The "long" format is the standard for plotting libraries like Seaborn.
    processed_records = []
    for index, row in df.iterrows():
        for col_name in metric_cols:
            try:
                # Safely evaluate the string to a dictionary
                metric_dict = ast.literal_eval(row[col_name])
                
                # Create a new record for the long-format DataFrame
                processed_records.append({
                    'model_type': row["model_type"],
                    'in_domain': row['in_domain'],
                    'dataset_test': row['dataset_test'],
                    'dataset_train': row["dataset_train"],
                    'metric': metric_name_map.get(col_name, col_name),
                    'metric_category': metric_to_category.get(col_name, "Other"),
                    'mean_score': metric_dict.get('mean', pd.NA),
                    'std_dev': metric_dict.get('std', pd.NA)
                })
            except (ValueError, SyntaxError):
                # Handle cases where the cell might be empty or malformed
                print(f"Could not parse row {index}, column {col_name}. Skipping.")
    df_long = pd.DataFrame(processed_records)

    return df, df_long

In [18]:
results_df, df_long = load_aggregated_results(f"{PROJECT_DIR}/results/experiments/aggregated_results.csv")

results_df

Could not parse row 40, column moverscore. Skipping.
Could not parse row 40, column bertscore_f1. Skipping.
Could not parse row 40, column bertscore_precision. Skipping.
Could not parse row 40, column bertscore_recall. Skipping.

    run_id                          model           dataset split                                  unieval_relevance                                 unieval_factuality                                       rouge_rouge1                                       rouge_rougeL                                    rouge_rougeLsum                                         moverscore                                       bertscore_f1                                bertscore_precision                                   bertscore_recall                                    unieval_fluency                                  unieval_coherence                               compression_sentence                                  compression_token  dataset_test dataset_train          model_type  in_domain
0        1                   ground_truth  convosumm/reddit  test  {'mean': 0.9855425109640278, 'std': 0.03131239...  {'mean': 0.7127423688060528, 'std': 0.14718363...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 0.9999999418258667, 'std': 1.38295929...  {'mean': 0.9999999418258667, 'std': 1.38295929...  {'mean': 0.9999999418258667, 'std': 1.38295929...  {'mean': 0.8962882354893531, 'std': 0.09558429...  {'mean': 0.729176020702826, 'std': 0.208525265...  {'mean': 0.10242261517227712, 'std': 0.0485502...  {'mean': 0.14928181353158385, 'std': 0.0799263...  Conv. Reddit  Conv. Reddit        ground_truth       True
1        2  allenai/PRIMERA-multixscience  convosumm/reddit  test  {'mean': 0.5976378536643414, 'std': 0.27521109...  {'mean': 0.5085267988744268, 'std': 0.15112957...  {'mean': 0.21164999766803447, 'std': 0.0578874...  {'mean': 0.12443743614989292, 'std': 0.0324015...  {'mean': 0.12443743614989292, 'std': 0.0324015...  {'mean': 0.012527305853438704, 'std': 0.062514...  {'mean': -0.000358729700135882, 'std': 0.06785...  {'mean': -0.07653766959253698, 'std': 0.077606...  {'mean': 0.08139306873828173, 'std': 0.0705534...  {'mean': 0.5998391898054409, 'std': 0.17913964...  {'mean': 0.6405243598933591, 'std': 0.24893135...  {'mean': 0.23586857258883323, 'std': 0.1528116...  {'mean': 0.40346470180961297, 'std': 0.2337040...  Conv. Reddit      XScience             PRIMERA      False
2        3              PRIMERA-ConvoSumm  convosumm/reddit  test  {'mean': 0.731714465971771, 'std': 0.254093978...  {'mean': 0.6483481734150773, 'std': 0.17214836...  {'mean': 0.36554962848924616, 'std': 0.0757385...  {'mean': 0.23304234760069606, 'std': 0.0554475...  {'mean': 0.23304234760069606, 'std': 0.0554475...  {'mean': 0.08901442503237685, 'std': 0.0763412...  {'mean': 0.21177772682905197, 'std': 0.0850327...  {'mean': 0.21977261752355845, 'std': 0.0931853...  {'mean': 0.1992487983852625, 'std': 0.08940725...  {'mean': 0.9152546237628535, 'std': 0.07876620...  {'mean': 0.7131287797315868, 'std': 0.23298629...  {'mean': 0.09956075453627942, 'std': 0.0396044...  {'mean': 0.13331725384642562, 'std': 0.0629207...  Conv. Reddit  Conv. Reddit             PRIMERA       True
3        4         PRIMERA-MultiNews_Plus  convosumm/reddit  test  {'mean': 0.4663545987961307, 'std': 0.28373713...  {'mean': 0.9543511345592296, 'std': 0.08808043...  {'mean': 0.2052130924087042, 'std': 0.07015013...  {'mean': 0.11616032503358079, 'std': 0.0404427...  {'mean': 0.11616032503358079, 'std': 0.0404427...  {'mean': -0.011123763904697138, 'std': 0.07067...  {'mean': -0.03426252436544746, 'std': 0.106407...  {'mean': -0.11852404737100006, 'std': 0.120503...  {'mean': 0.06349818559701088, 'std': 0.1133708...  {'mean': 0.6916803453213957, 'std': 0.15235310...  {'mean': 0.9178626854662283, 'std': 0.17835100...  {'mean': 0.31899975411562603, 'std': 0.3375974...  {'mean': 0.3909981052937315, 'std': 0.33212922...  Conv. Reddit         News+             PRIMERA      False
4        5            SummN-MultiXScience  convosumm/reddit  test  {'mean': 0.6236892103003036, 'std': 0.36479893...  {'mean': 0.2434601452116484, 'std': 0.25441539...  {'mean': 0.1119149225522074, 'std': 0.06172212...  {'mean': 0.09801577616872328, 'std': 0.0466282...  {'mean': 0.09801577616872328, 'std': 0.0466282...  {'mean': -0.15609310382533664, 'std': 0.076291...  {'mean': -0.24424022296071052, 'std': 0.127346...  {'mean': -0.3176295380759984, 'std': 0.1361264...  {'mean': -0.15838947359193117, 'std': 0.138660...  {'mean': 0.8053866430683386, 'std': 0.24364602...  {'mean': 0.575846709246058, 'std': 0.303174024...  {'mean': 0.20716038853030794, 'std': 0.1211811...  {'mean': 0.4458740528118649, 'std': 0.30143277...  Conv. Reddit      XScience               SummN      False
5        6                SummN-ConvoSumm  convosumm/reddit  test  {'mean': 0.6282741425434174, 'std': 0.33000325...  {'mean': 0.645556680797106, 'std': 0.190470278...  {'mean': 0.3471162029771905, 'std': 0.08563307...  {'mean': 0.23011761487944812, 'std': 0.0613364...  {'mean': 0.23011761487944812, 'std': 0.0613364...  {'mean': 0.07011291424208428, 'std': 0.0877327...  {'mean': 0.181617968733015, 'std': 0.121727514...  {'mean': 0.18553726537618787, 'std': 0.1333445...  {'mean': 0.17323308256524614, 'std': 0.1205932...  {'mean': 0.8876348462112628, 'std': 0.12478895...  {'mean': 0.6214302695497963, 'std': 0.30772143...  {'mean': 0.09365020598256175, 'std': 0.0368782...  {'mean': 0.14630390247363884, 'std': 0.1892154...  Conv. Reddit  Conv. Reddit               SummN       True
6        7           SummN-MultiNews_Plus  convosumm/reddit  test  {'mean': 0.654418250926556, 'std': 0.289387559...  {'mean': 0.6767987037624811, 'std': 0.19118765...  {'mean': 0.17402859620800842, 'std': 0.0847073...  {'mean': 0.10238501027798998, 'std': 0.0433213...  {'mean': 0.10238501027798998, 'std': 0.0433213...  {'mean': -0.03920901958642605, 'std': 0.081733...  {'mean': -0.09623762227979023, 'std': 0.165818...  {'mean': -0.19272994574625046, 'std': 0.171570...  {'mean': 0.021304604426492006, 'std': 0.170995...  {'mean': 0.6834458621559883, 'std': 0.17963982...  {'mean': 0.6731268617256743, 'std': 0.29297280...  {'mean': 0.4841095978626732, 'std': 0.53738347...  {'mean': 0.712518197713564, 'std': 0.594047146...  Conv. Reddit         News+               SummN      False
7        8        ConvoSumm-MultiXScience  convosumm/reddit  test  {'mean': 0.23271219252501094, 'std': 0.1989364...  {'mean': 0.4617297742821378, 'std': 0.21313557...  {'mean': 0.23751470655198914, 'std': 0.0715893...  {'mean': 0.15638026668050434, 'std': 0.0412634...  {'mean': 0.15638026668050434, 'std': 0.0412634...  {'mean': -0.016819698894512135, 'std': 0.08323...  {'mean': -0.005807091554976068, 'std': 0.08320...  {'mean': -0.026699044054956177, 'std': 0.09483...  {'mean': 0.010207172326365253, 'std': 0.087351...  {'mean': 0.5827484736665433, 'std': 0.16028175...  {'mean': 0.2481154905642099, 'std': 0.19207227...  {'mean': 0.1275632492608004, 'std': 0.07990455...  {'mean': 0.1538817132289404, 'std': 0.10386908...  Conv. Reddit      XScience           ConvoSumm      False
8        9            ConvoSumm-ConvoSumm  convosumm/reddit  test  {'mean': 0.6982185812416573, 'std': 0.26088877...  {'mean': 0.6448624135535097, 'std': 0.17299755...  {'mean': 0.3456994183202994, 'std': 0.07937975...  {'mean': 0.23666016157326963, 'std': 0.0602634...  {'mean': 0.23666016157326963, 'std': 0.0602634...  {'mean': 0.05569252966819346, 'std': 0.0785883...  {'mean': 0.20502467449428513, 'std': 0.0880822...  {'mean': 0.24997340177744626, 'std': 0.0985029...  {'mean': 0.15908057161769829, 'std': 0.0928923...  {'mean': 0.9145819456531356, 'std': 0.08011682...  {'mean': 0.5996400811017836, 'std': 0.26917901...  {'mean': 0.08627995240334656, 'std': 0.0333127...  {'mean': 0.09375520659701664, 'std': 0.0456994...  Conv. Reddit  Conv. Reddit           ConvoSumm       True
9       10       ConvoSumm-MultiNews_Plus  convosumm/reddit  test  {'mean': 0.7576750387866421, 'std': 0.22818075...  {'mean': 0.6969226520006567, 'std': 0.15729542...  {'mean': 0.24564785585251425, 'std': 0.0614817...  {'mean': 0.13897168221973727, 'std': 0.0386524...  {'mean': 0.13897168221973727, 'std': 0.0386524...  {'mean': 0.0076682235185645785, 'std': 0.06541...  {'mean': 0.033624608907150105, 'std': 0.070168...  {'mean': -0.038480741038743875, 'std': 0.08098...  {'mean': 0.1101896934658289, 'std': 0.07127021...  {'mean': 0.6989360899262449, 'std': 0.14114847...  {'mean': 0.7797604320135647, 'std': 0.21868723...  {'mean': 0.2920154690639623, 'std': 0.16863733...  {'mean': 0.37965484246490244, 'std': 0.2395838...  Conv. Reddit         News+           ConvoSumm      False
10      11                            ICL  convosumm/reddit  test  {'mean': 0.9301935826211097, 'std': 0.09975392...  {'mean': 0.8096870710817732, 'std': 0.10384114...  {'mean': 0.21004168205661128, 'std': 0.0566239...  {'mean': 0.12343267351750159, 'std': 0.0298914...  {'mean': 0.1527231908288355, 'std': 0.03723915...  {'mean': 0.04066218875162067, 'std': 0.0615083...  {'mean': 0.046684353062883016, 'std': 0.075383...  {'mean': -0.06334441642946331, 'std': 0.083855...  {'mean': 0.17653109844587744, 'std': 0.0728760...  {'mean': 0.8957709776315665, 'std': 0.10692703...  {'mean': 0.941643012871146, 'std': 0.105849921...  {'mean': 0.3143674923565236, 'std': 0.14070590...  {'mean': 0.5824807158315694, 'std': 0.25667428...  Conv. Reddit     zero-shot  Llama 3.1 (0-shot)      False
11      12           ICL-convosumm/reddit  convosumm/reddit  test  {'mean': 0.9313366938207789, 'std': 0.08357116...  {'mean': 0.5872873236521206, 'std': 0.09210759...  {'mean': 0.17976190559934208, 'std': 0.0424022...  {'mean': 0.10352020129185391, 'std': 0.0241736...  {'mean': 0.13519034967518828, 'std': 0.0325995...  {'mean': 0.03793396418500733, 'std': 0.0618062...  {'mean': -0.001564183747046627, 'std': 0.06439...  {'mean': -0.13526798881217839, 'std': 0.062149...  {'mean': 0.16794952538562938, 'std': 0.0810284...  {'mean': 0.8334433239182426, 'std': 0.06658379...  {'mean': 0.915300647516416, 'std': 0.081339361...  {'mean': 0.5189607589910672, 'std': 0.22495755...  {'mean': 0.7418452260994459, 'std': 0.37424116...  Conv. Reddit  Conv. Reddit           Llama 3.1       True
12      13              ICL-multixscience  convosumm/reddit  test  {'mean': 0.9415796379977971, 'std': 0.10494085...  {'mean': 0.5294130719683657, 'std': 0.11810771...  {'mean': 0.12266146579688501, 'std': 0.0370439...  {'mean': 0.07760538826952475, 'std': 0.0199099...  {'mean': 0.09478267471875122, 'std': 0.0260689...  {'mean': -0.00397837912211068, 'std': 0.054484...  {'mean': -0.07332570029469207, 'std': 0.072596...  {'mean': -0.20871417063102127, 'std': 0.075574...  {'mean': 0.10403498569875956, 'std': 0.0841897...  {'mean': 0.9175860463951773, 'std': 0.06394599...  {'mean': 0.9265081404197785, 'std': 0.10057693...  {'mean': 0.5403141429948068, 'std': 0.24942111...  {'mean': 1.1242751431939266, 'std': 0.63375459...  Conv. Reddit      XScience           Llama 3.1      False
13      14             ICL-multinews_plus  convosumm/reddit  test  {'mean': 0.8980302166504914, 'std': 0.11849038...  {'mean': 0.4299735363935959, 'std': 0.12539870...  {'mean': 0.17517282513786245, 'std': 0.0402446...  {'mean': 0.10143222356770216, 'std': 0.0209324...  {'mean': 0.12796996545926448, 'std': 0.0292708...  {'mean': 0.008448361857691319, 'std': 0.057560...  {'mean': 0.030573203495005145, 'std': 0.057616...  {'mean': -0.08458719210629352, 'std': 0.053559...  {'mean': 0.16784999619796873, 'std': 0.0759213...  {'mean': 0.9327730347298911, 'std': 0.06678243...  {'mean': 0.8784515446082362, 'std': 0.11264562...  {'mean': 0.3465973283000711, 'std': 0.13465372...  {'mean': 0.7090645664642821, 'std': 0.35125730...  Conv. Reddit         News+           Llama 3.1      False
14      15                   ground_truth     multixscience  test  {'mean': 0.9882119079711595, 'std': 0.00487189...  {'mean': 0.55045862527962, 'std': 0.1699324311...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 1.0, 'std': 0.0, 'ci': (1.0, 1.0), 'c...  {'mean': 0.9999999999630959, 'std': 9.54470483...  {'mean': 0.9999999503973971, 'std': 1.11861225...  {'mean': 0.9999999503973971, 'std': 1.11861225...  {'mean': 0.9999999503973971, 'std': 1.11861225...  {'mean': 0.6562540899402792, 'std': 0.18345060...  {'mean': 0.4282043861720864, 'std': 0.27336150...  {'mean': 0.25596776525611636, 'std': 0.1814160...  {'mean': 0.2494609706815477, 'std': 0.17271714...      XScience      XScience        ground_truth       True
15      16  allenai/PRIMERA-multixscience     multixscience  test  {'mean': 0.6788103229283178, 'std': 0.28731378...  {'mean': 0.9576532269923294, 'std': 0.07508948...  {'mean': 0.2714986659074747, 'std': 0.08645241...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.04760233778061149, 'std': 0.0742059...  {'mean': 0.05220993124061019, 'std': 0.0938891...  {'mean': 0.037219902011884305, 'std': 0.107345...  {'mean': 0.06399044265126691, 'std': 0.1021842...  {'mean': 0.8256598812086077, 'std': 0.12455661...  {'mean': 0.8559797416270376, 'std': 0.25045741...  {'mean': 0.3316927005238074, 'std': 0.21857835...  {'mean': 0.3685896961292324, 'std': 0.25131351...      XScience      XScience             PRIMERA       True
16      17              PRIMERA-ConvoSumm     multixscience  test  {'mean': 0.6788103229283178, 'std': 0.28731378...  {'mean': 0.9576532269923294, 'std': 0.07508948...  {'mean': 0.2714986659074747, 'std': 0.08645241...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.04760233778061149, 'std': 0.0742059...  {'mean': 0.05220993089185414, 'std': 0.0938891...  {'mean': 0.03721990043044861, 'std': 0.1073454...  {'mean': 0.06399044357309745, 'std': 0.1021842...  {'mean': 0.8256598812086077, 'std': 0.12455661...  {'mean': 0.8559797416270376, 'std': 0.25045741...  {'mean': 0.3316927005238074, 'std': 0.21857835...  {'mean': 0.3685896961292324, 'std': 0.25131351...      XScience  Conv. Reddit             PRIMERA      False
17      18         PRIMERA-MultiNews_Plus     multixscience  test  {'mean': 0.6788103229283178, 'std': 0.28731378...  {'mean': 0.9576532269923294, 'std': 0.07508948...  {'mean': 0.2714986659074747, 'std': 0.08645241...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.14486497299506984, 'std': 0.0457466...  {'mean': 0.04760233778061149, 'std': 0.0742059...  {'mean': 0.05220993079185087, 'std': 0.0938891...  {'mean': 0.03721990066315677, 'std': 0.1073454...  {'mean': 0.0639904427723364, 'std': 0.10218427...  {'mean': 0.8256598812086077, 'std': 0.12455661...  {'mean': 0.8559797416270376, 'std': 0.25045741...  {'mean': 0.3316927005238074, 'std': 0.21857835...  {'mean': 0.3685896961292324, 'std': 0.25131351...      XScience         News+             PRIMERA      False
18      19            SummN-MultiXScience     multixscience  test  {'mean': 0.3559362048794685, 'std': 0.28720355...  {'mean': 0.497795740849181, 'std': 0.253503862...  {'mean': 0.18187893296048735, 'std': 0.1061572...  {'mean': 0.12935411182085593, 'std': 0.0673962...  {'mean': 0.12935411182085593, 'std': 0.0673962...  {'mean': -0.08435929274359584, 'std': 0.093348...  {'mean': -0.11609408209892308, 'std': 0.146048...  {'mean': -0.06024887410359889, 'std': 0.149841...  {'mean': -0.15286846234573953, 'std': 0.188332...  {'mean': 0.5687603504881652, 'std': 0.28226800...  {'mean': 0.24820081380866374, 'std': 0.2746079...  {'mean': 0.29186665670110934, 'std': 0.2503960...  {'mean': 0.4602236443313337, 'std': 0.33573412...      XScience      XScience               SummN       True
19      20                SummN-ConvoSumm     multixscience  test  {'mean': 0.6168391197780247, 'std': 0.29452675...  {'mean': 0.8156854546528806, 'std': 0.18308325...  {'mean': 0.2414693031823322, 'std': 0.06902784...  {'mean': 0.14740509073188518, 'std': 0.0439237...  {'mean': 0.14740509073188518, 'std': 0.0439237...  {'mean': 0.01472309313463207, 'std': 0.0714283...  {'mean': 0.06854785047871874, 'std': 0.0783413...  {'mean': 0.14796507618847357, 'std': 0.0900630...  {'mean': -0.005271359727062863, 'std': 0.08626...  {'mean': 0.9244165723605089, 'std': 0.07623585...  {'mean': 0.8128981568067907, 'std': 0.29546288...  {'mean': 0.16137747792500856, 'std': 0.0926234...  {'mean': 0.12040957948489371, 'std': 0.0863375...      XScience  Conv. Reddit               SummN      False
20      21           SummN-MultiNews_Plus     multixscience  test  {'mean': 0.5043233598637233, 'std': 0.32084424...  {'mean': 0.6676078190392661, 'std': 0.15328226...  {'mean': 0.20632047382808058, 'std': 0.0717538...  {'mean': 0.12263521990071208, 'std': 0.0350253...  {'mean': 0.12263521990071208, 'std': 0.0350253...  {'mean': 0.012034130404695363, 'std': 0.067448...  {'mean': -0.01796374731513739, 'std': 0.074717...  {'mean': -0.0668597357703964, 'std': 0.0847491...  {'mean': 0.030422872469947043, 'std': 0.081954...  {'mean': 0.7404493159571194, 'std': 0.13175975...  {'mean': 0.5389323668340349, 'std': 0.31402283...  {'mean': 0.6019595271731095, 'std': 0.36881263...  {'mean': 0.6953878131032019, 'std': 0.41410012...      XScience         News+               SummN      False
21      22        ConvoSumm-MultiXScience     multixscience  test  {'mean': 0.49514974035656373, 'std': 0.2640962...  {'mean': 0.6019801204866789, 'std': 0.19315777...  {'mean': 0.3132250515086414, 'std': 0.07582806...  {'mean': 0.1784562381418831, 'std': 0.04222057...  {'mean': 0.1784562381418831, 'std': 0.04222057...  {'mean': 0.03755354803180345, 'std': 0.0750054...  {'mean': 0.08876770363017321, 'std': 0.0716118...  {'mean': 0.10683505424212887, 'std': 0.0927750...  {'mean': 0.06861048852000887, 'std': 0.0831507...  {'mean': 0.6915460615425205, 'std': 0.18183868...  {'mean': 0.37778838424487277, 'std': 0.2556917...  {'mean': 0.27560947678110276, 'std': 0.1860894...  {'mean': 0.2120810185898322, 'std': 0.13519400...      XScience      XScience           ConvoSumm       True
22      23            ConvoSumm-ConvoSumm     multixscience  test  {'mean': 0.6345472863330412, 'std': 0.25266562...  {'mean': 0.682025851830335, 'std': 0.179578967...  {'mean': 0.25401742399494953, 'std': 0.0678087...  {'mean': 0.15095311650616866, 'std': 0.0367880...  {'mean': 0.15095311650616866, 'std': 0.0367880...  {'mean': 0.015659057391949484, 'std': 0.064985...  {'mean': 0.0525282441287392, 'std': 0.06727649...  {'mean': 0.11305116901116868, 'std': 0.0713272...  {'mean': -0.006225114584249423, 'std': 0.08417...  {'mean': 0.9081406222696116, 'std': 0.08209865...  {'mean': 0.6100873142665928, 'std': 0.29248525...  {'mean': 0.24134258776327724, 'std': 0.1449769...  {'mean': 0.15452873914995896, 'std': 0.1029052...      XScience  Conv. Reddit           ConvoSumm      False
23      24       ConvoSumm-MultiNews_Plus     multixscience  test  {'mean': 0.6870664698608385, 'std': 0.27216630...  {'mean': 0.706405787912453, 'std': 0.142851109...  {'mean': 0.26903819560603587, 'std': 0.0748431...  {'mean': 0.1450145482553656, 'std': 0.03302220...  {'mean': 0.1450145482553656, 'std': 0.03302220...  {'mean': 0.03695046954599075, 'std': 0.0587515...  {'mean': 0.04356434280220729, 'std': 0.0576025...  {'mean': 0.02390944937879629, 'std': 0.0650160...  {'mean': 0.05824887576840112, 'std': 0.0700816...  {'mean': 0.8198440605392346, 'std': 0.08930016...  {'mean': 0.6946578083897191, 'std': 0.27633526...  {'mean': 0.4485049303890214, 'std': 0.29059609...  {'mean': 0.45051130109802096, 'std': 0.2795216...      XScience         News+           ConvoSumm      False

In [19]:
df_long

       model_type  in_domain  dataset_test dataset_train       metric          metric_category  mean_score  std_dev
0    ground_truth       True  Conv. Reddit  Conv. Reddit    Rel. (UE)  Ground-Truth Similarity        0.99     0.03
1    ground_truth       True  Conv. Reddit  Conv. Reddit   Fact. (UE)               Factuality        0.71     0.15
2    ground_truth       True  Conv. Reddit  Conv. Reddit          R-1  Ground-Truth Similarity        1.00     0.00
3    ground_truth       True  Conv. Reddit  Conv. Reddit          R-L  Ground-Truth Similarity        1.00     0.00
4    ground_truth       True  Conv. Reddit  Conv. Reddit       R-LSum  Ground-Truth Similarity        1.00     0.00
..            ...        ...           ...           ...          ...                      ...         ...      ...
537     Llama 3.1       True         News+         News+     BERTS. R  Ground-Truth Similarity       -0.03     0.04
538     Llama 3.1       True         News+         News+   Flue. (UE)                  Quality        0.95     0.03
539     Llama 3.1       True         News+         News+    Coh. (UE)                  Quality        0.77     0.20
540     Llama 3.1       True         News+         News+  Comp.-Sent.                  Quality        0.68     0.27
541     Llama 3.1       True         News+         News+   Comp.-Word                  Quality        0.74     0.26

[542 rows x 8 columns]

# Q: Which model is the best in-domain?

In [23]:
in_domain = df_long[df_long.in_domain].copy()
in_domain.set_index(["metric_category", "model_type", "dataset_train"]).sort_index()

                                                    in_domain  dataset_test       metric  mean_score  std_dev
metric_category         model_type   dataset_train
Factuality              ConvoSumm    Conv. Reddit        True  Conv. Reddit   Fact. (UE)        0.64     0.17
                                     News+               True         News+   Fact. (UE)        0.14     0.10
                                     XScience            True      XScience   Fact. (UE)        0.60     0.19
                        Llama 3.1    Conv. Reddit        True  Conv. Reddit   Fact. (UE)        0.59     0.09
                                     News+               True         News+   Fact. (UE)        0.11     0.08
                                     XScience            True      XScience   Fact. (UE)        0.63     0.12
                        PRIMERA      Conv. Reddit        True  Conv. Reddit   Fact. (UE)        0.65     0.17
                                     News+               True         News+   Fact. (UE)        0.19     0.17
                                     XScience            True      XScience   Fact. (UE)        0.96     0.08
                        SummN        Conv. Reddit        True  Conv. Reddit   Fact. (UE)        0.65     0.19
                                     News+               True         News+   Fact. (UE)        0.14     0.12
                                     XScience            True      XScience   Fact. (UE)        0.50     0.25
                        ground_truth Conv. Reddit        True  Conv. Reddit   Fact. (UE)        0.71     0.15
                                     News+               True         News+   Fact. (UE)        0.70     0.12
                                     XScience            True      XScience   Fact. (UE)        0.55     0.17
Ground-Truth Similarity ConvoSumm    Conv. Reddit        True  Conv. Reddit    Rel. (UE)        0.70     0.26
                                     Conv. Reddit        True  Conv. Reddit          R-1        0.35     0.08
                                     Conv. Reddit        True  Conv. Reddit          R-L        0.24     0.06
                                     Conv. Reddit        True  Conv. Reddit       R-LSum        0.24     0.06
                                     Conv. Reddit        True  Conv. Reddit       Mover.        0.06     0.08
                                     Conv. Reddit        True  Conv. Reddit    BERTS. F1        0.21     0.09
                                     Conv. Reddit        True  Conv. Reddit     BERTS. P        0.25     0.10
                                     Conv. Reddit        True  Conv. Reddit     BERTS. R        0.16     0.09
                                     News+               True         News+    Rel. (UE)        0.79     0.18
                                     News+               True         News+          R-1        0.24     0.04
                                     News+               True         News+          R-L        0.12     0.02
                                     News+               True         News+       R-LSum        0.12     0.02
                                     News+               True         News+       Mover.       -0.08     0.04
                                     News+               True         News+    BERTS. F1       -0.02     0.04
                                     News+               True         News+     BERTS. P       -0.01     0.05
                                     News+               True         News+     BERTS. R       -0.03     0.05
                                     XScience            True      XScience    Rel. (UE)        0.50     0.26
                                     XScience            True      XScience          R-1        0.31     0.08
                                     XScience            True      XScience          R-L        0.18     0.04
                                     XScience            True      XScience       R-LSum        0.18     0.04
                                     XScience            True      XScience       Mover.        0.04     0.08
                                     XScience            True      XScience    BERTS. F1        0.09     0.07
                                     XScience            True      XScience     BERTS. P        0.11     0.09
                                     XScience            True      XScience     BERTS. R        0.07     0.08
                        Llama 3.1    Conv. Reddit        True  Conv. Reddit    Rel. (UE)        0.93     0.08
                                     Conv. Reddit        True  Conv. Reddit          R-1        0.18     0.04
                                     Conv. Reddit        True  Conv. Reddit          R-L        0.10     0.02
                                     Conv. Reddit        True  Conv. Reddit       R-LSum        0.14     0.03
                                     Conv. Reddit        True  Conv. Reddit       Mover.        0.04     0.06
                                     Conv. Reddit        True  Conv. Reddit    BERTS. F1       -0.00     0.06
                                     Conv. Reddit        True  Conv. Reddit     BERTS. P       -0.14     0.06
                                     Conv. Reddit        True  Conv. Reddit     BERTS. R        0.17     0.08
                                     News+               True         News+    Rel. (UE)        0.86     0.16
                                     News+               True         News+          R-1        0.25     0.04
                                     News+               True         News+          R-L        0.12     0.02
                                     News+               True         News+       R-LSum        0.15     0.02
                                     News+               True         News+       Mover.       -0.08     0.04
                                     News+               True         News+    BERTS. F1       -0.03     0.04
                                     News+               True         News+     BERTS. P       -0.04     0.04
                                     News+               True         News+     BERTS. R       -0.03     0.04
                                     XScience            True      XScience    Rel. (UE)        0.92     0.14
                                     XScience            True      XScience          R-1        0.19     0.07
                                     XScience            True      XScience          R-L        0.10     0.03
                                     XScience            True      XScience       R-LSum        0.13     0.04
                                     XScience            True      XScience       Mover.        0.06     0.06
                                     XScience            True      XScience    BERTS. F1       -0.02     0.07
                                     XScience            True      XScience     BERTS. P       -0.10     0.08
                                     XScience            True      XScience     BERTS. R        0.08     0.07
                        PRIMERA      Conv. Reddit        True  Conv. Reddit    Rel. (UE)        0.73     0.25
                                     Conv. Reddit        True  Conv. Reddit          R-1        0.37     0.08
                                     Conv. Reddit        True  Conv. Reddit          R-L        0.23     0.06
                                     Conv. Reddit        True  Conv. Reddit       R-LSum        0.23     0.06
                                     Conv. Reddit        True  Conv. Reddit       Mover.        0.09     0.08
                                     Conv. Reddit        True  Conv. Reddit    BERTS. F1        0.21     0.09
                                     Conv. Reddit        True  Conv. Reddit     BERTS. P        0.22     0.09
                                     Conv. Reddit        True  Conv. Reddit     BERTS. R        0.20     0.09
                                     News+               True         News+    Rel. (UE)        0.45     0.31
                                     News+               True         News+          R-1        0.21     0.05
                                     News+               True         News+          R-L        0.11     0.02
                                     News+               True         News+       R-LSum        0.11     0.02
                                     News+               True         News+       Mover.       -0.10     0.04
                                     News+               True         News+    BERTS. F1       -0.06     0.07
                                     News+               True         News+     BERTS. P       -0.05     0.08
                                     News+               True         News+     BERTS. R       -0.08     0.08
                                     XScience            True      XScience    Rel. (UE)        0.68     0.29
                                     XScience            True      XScience          R-1        0.27     0.09
                                     XScience            True      XScience          R-L        0.14     0.05
                                     XScience            True      XScience       R-LSum        0.14     0.05
                                     XScience            True      XScience       Mover.        0.05     0.07
                                     XScience            True      XScience    BERTS. F1        0.05     0.09
                                     XScience            True      XScience     BERTS. P        0.04     0.11
                                     XScience            True      XScience     BERTS. R        0.06     0.10
                        SummN        Conv. Reddit        True  Conv. Reddit    Rel. (UE)        0.63     0.33
                                     Conv. Reddit        True  Conv. Reddit          R-1        0.35     0.09
                                     Conv. Reddit        True  Conv. Reddit          R-L        0.23     0.06
                                     Conv. Reddit        True  Conv. Reddit       R-LSum        0.23     0.06
                                     Conv. Reddit        True  Conv. Reddit       Mover.        0.07     0.09
                                     Conv. Reddit        True  Conv. Reddit    BERTS. F1        0.18     0.12
                                     Conv. Reddit        True  Conv. Reddit     BERTS. P        0.19     0.13
                                     Conv. Reddit        True  Conv. Reddit     BERTS. R        0.17     0.12
                                     News+               True         News+    Rel. (UE)        0.68     0.26
                                     News+               True         News+          R-1        0.23     0.05
                                     News+               True         News+          R-L        0.12     0.02
                                     News+               True         News+       R-LSum        0.12     0.02
                                     News+               True         News+       Mover.       -0.09     0.04
                                     News+               True         News+    BERTS. F1       -0.05     0.07
                                     News+               True         News+     BERTS. P       -0.06     0.08
                                     News+               True         News+     BERTS. R       -0.05     0.07
                                     XScience            True      XScience    Rel. (UE)        0.36     0.29
                                     XScience            True      XScience          R-1        0.18     0.11
                                     XScience            True      XScience          R-L        0.13     0.07
                                     XScience            True      XScience       R-LSum        0.13     0.07
                                     XScience            True      XScience       Mover.       -0.08     0.09
                                     XScience            True      XScience    BERTS. F1       -0.12     0.15
                                     XScience            True      XScience     BERTS. P       -0.06     0.15
                                     XScience            True      XScience     BERTS. R       -0.15     0.19
                        ground_truth Conv. Reddit        True  Conv. Reddit    Rel. (UE)        0.99     0.03
                                     Conv. Reddit        True  Conv. Reddit          R-1        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit          R-L        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit       R-LSum        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit       Mover.        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit    BERTS. F1        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit     BERTS. P        1.00     0.00
                                     Conv. Reddit        True  Conv. Reddit     BERTS. R        1.00     0.00
                                     News+               True         News+    Rel. (UE)        0.98     0.04
                                     News+               True         News+          R-1        1.00     0.00
                                     News+               True         News+          R-L        1.00     0.00
                                     News+               True         News+       R-LSum        1.00     0.00
                                     News+               True         News+       Mover.        1.00     0.00
                                     News+               True         News+    BERTS. F1        1.00     0.00
                                     News+               True         News+     BERTS. P        1.00     0.00
                                     News+               True         News+     BERTS. R        1.00     0.00
                                     XScience            True      XScience    Rel. (UE)        0.99     0.00
                                     XScience            True      XScience          R-1        1.00     0.00
                                     XScience            True      XScience          R-L        1.00     0.00
                                     XScience            True      XScience       R-LSum        1.00     0.00
                                     XScience            True      XScience       Mover.        1.00     0.00
                                     XScience            True      XScience    BERTS. F1        1.00     0.00
                                     XScience            True      XScience     BERTS. P        1.00     0.00
                                     XScience            True      XScience     BERTS. R        1.00     0.00
Quality                 ConvoSumm    Conv. Reddit        True  Conv. Reddit   Flue. (UE)        0.91     0.08
                                     Conv. Reddit        True  Conv. Reddit    Coh. (UE)        0.60     0.27
                                     Conv. Reddit        True  Conv. Reddit  Comp.-Sent.        0.09     0.03
                                     Conv. Reddit        True  Conv. Reddit   Comp.-Word        0.09     0.05
                                     News+               True         News+   Flue. (UE)        0.75     0.12
                                     News+               True         News+    Coh. (UE)        0.74     0.18
                                     News+               True         News+  Comp.-Sent.        0.53     0.25
                                     News+               True         News+   Comp.-Word        0.46     0.19
                                     XScience            True      XScience   Flue. (UE)        0.69     0.18
                                     XScience            True      XScience    Coh. (UE)        0.38     0.26
                                     XScience            True      XScience  Comp.-Sent.        0.28     0.19
                                     XScience            True      XScience   Comp.-Word        0.21     0.14
                        Llama 3.1    Conv. Reddit        True  Conv. Reddit   Flue. (UE)        0.83     0.07
                                     Conv. Reddit        True  Conv. Reddit    Coh. (UE)        0.92     0.08
                                     Conv. Reddit        True  Conv. Reddit  Comp.-Sent.        0.52     0.22
                                     Conv. Reddit        True  Conv. Reddit   Comp.-Word        0.74     0.37
                                     News+               True         News+   Flue. (UE)        0.95     0.03
                                     News+               True         News+    Coh. (UE)        0.77     0.20
                                     News+               True         News+  Comp.-Sent.        0.68     0.27
                                     News+               True         News+   Comp.-Word        0.74     0.26
                                     XScience            True      XScience   Flue. (UE)        0.90     0.07
                                     XScience            True      XScience    Coh. (UE)        0.95     0.07
                                     XScience            True      XScience  Comp.-Sent.        1.18     0.68
                                     XScience            True      XScience   Comp.-Word        1.14     0.67
                        PRIMERA      Conv. Reddit        True  Conv. Reddit   Flue. (UE)        0.92     0.08
                                     Conv. Reddit        True  Conv. Reddit    Coh. (UE)        0.71     0.23
                                     Conv. Reddit        True  Conv. Reddit  Comp.-Sent.        0.10     0.04
                                     Conv. Reddit        True  Conv. Reddit   Comp.-Word        0.13     0.06
                                     News+               True         News+   Flue. (UE)        0.66     0.17
                                     News+               True         News+    Coh. (UE)        0.46     0.28
                                     News+               True         News+  Comp.-Sent.        0.40     0.41
                                     News+               True         News+   Comp.-Word        0.43     0.30
                                     XScience            True      XScience   Flue. (UE)        0.83     0.12
                                     XScience            True      XScience    Coh. (UE)        0.86     0.25
                                     XScience            True      XScience  Comp.-Sent.        0.33     0.22
                                     XScience            True      XScience   Comp.-Word        0.37     0.25
                        SummN        Conv. Reddit        True  Conv. Reddit   Flue. (UE)        0.89     0.12
                                     Conv. Reddit        True  Conv. Reddit    Coh. (UE)        0.62     0.31
                                     Conv. Reddit        True  Conv. Reddit  Comp.-Sent.        0.09     0.04
                                     Conv. Reddit        True  Conv. Reddit   Comp.-Word        0.15     0.19
                                     News+               True         News+   Flue. (UE)        0.73     0.15
                                     News+               True         News+    Coh. (UE)        0.65     0.24
                                     News+               True         News+  Comp.-Sent.        0.67     0.55
                                     News+               True         News+   Comp.-Word        0.60     0.29
                                     XScience            True      XScience   Flue. (UE)        0.57     0.28